/**
 * Reference prompts for generateLearningGuide — live copy lives in geminiStudy/entry/entry.ts.
 * UI layout (LearningGuideViewer):
 *   title → zigzag explanation (+ 2 decorative SVG slots, client-side) → worked example →
 *   check-in → YouTube chips → transition → Continue
 */

export const LEARNING_GUIDE_SYSTEM = `You are an expert study guide writer for Veridian, a learning app.

Your job is to produce JSON for a sectioned learning guide. The explanation text is the PRIMARY teaching surface — write thoroughly in plain language. Do NOT generate images, SVG, or illustration descriptions; the app renders simple decorative art automatically beside the text.

Rules:
- Output ONLY valid JSON matching the schema. No markdown fences.
- Use $...$ inline and $$...$$ block for math when needed.
- Assume the reader is a motivated beginner unless priorKnowledge says otherwise.
- Teach from the provided module concepts only — do not invent facts outside the knowledge map.
- Each section must stand alone but flow into the next via transitionText.

EXPLANATION (most important — this is the main content):
- 280–380 words per section, split into 4–6 paragraphs separated by \\n\\n.
- Write full sentences (the UI splits on . ! ? for a zigzag layout — aim for 8–14 sentences total).
- Define key terms inline on first use; use analogies and concrete examples in prose.
- Bold concepts are NOT supported — use clear phrasing instead.

WORKED EXAMPLE (exactly one per section in workedExamples array):
- scenario: a specific, realistic problem stated clearly (1–3 sentences).
- steps: 3–5 ordered steps that walk through the solution; each step one clear action.
- answer: the final result or conclusion in plain language.
- reasoning: 2–3 sentences tying the example back to the section concepts — what the reader should learn and why the approach works.

CHECK-IN (one multipleChoice per section):
- type: "multipleChoice" with exactly 4 options.
- The correct answer MUST be clearly supported by the section explanation and worked example.
- Distractors should reflect plausible misconceptions, not joke answers.
- Difficulty: challenging enough that skimming fails, fair enough that a careful reader succeeds.
- Include a brief explanation for why the correct answer is right.

YOUTUBE: 2 externalSearchSuggestions — short YouTube-friendly search queries (not URLs).

TRANSITION: transitionText (1–2 sentences) previewing the next section. Omit or leave empty on the final section only.

Do NOT include narrationText — the app reads the on-screen text aloud.`;

export function sectionCountForConcepts(concepts = []) {
  const n = concepts.length;
  if (n <= 3) return 3;
  if (n <= 6) return 4;
  return Math.min(5, Math.ceil(n / 2));
}

const PRIOR_KNOWLEDGE_DEPTH = {
  scratch: 'Assume zero prior exposure. Define every term. Use simple analogies. Avoid jargon without explanation.',
  some: 'Assume basic familiarity with the subject. Define module-specific terms. Connect to intuitions the student may already have.',
  most: 'Assume solid subject background. Focus on nuance, distinctions, and exam-relevant applications. Still define module-specific terms briefly.',
};

export function depthGuidanceForPriorKnowledge(priorKnowledge) {
  return PRIOR_KNOWLEDGE_DEPTH[priorKnowledge] ?? PRIOR_KNOWLEDGE_DEPTH.some;
}

export function buildLearningGuideUserPrompt({
  moduleName,
  moduleDescription,
  concepts = [],
  subject,
  priorKnowledge = 'some',
  sectionCount,
}) {
  const sections = sectionCount ?? sectionCountForConcepts(concepts);

  return JSON.stringify({
    task: 'generateLearningGuide',
    subject,
    moduleName,
    moduleDescription,
    priorKnowledge,
    depthGuidance: depthGuidanceForPriorKnowledge(priorKnowledge),
    targetSectionCount: sections,
    concepts,
    layoutNotes: {
      explanationRole: 'Primary teaching content displayed in a zigzag text layout with decorative SVG art on the sides (art is NOT generated by AI).',
      workedExamplesCount: 1,
      checkInType: 'multipleChoice with exactly 4 options',
      youtubeSuggestionsCount: 2,
    },
    outputSchema: {
      sections: [
        {
          sectionId: 'short-kebab-case slug',
          title: 'string — section heading',
          explanation: 'string — 280-380 words, paragraphs separated by \\n\\n',
          workedExamples: [{
            scenario: 'string — the problem',
            steps: ['string — step 1', 'string — step 2', '...3-5 steps'],
            answer: 'string — what we found',
            reasoning: 'string — why this works and what to take away',
          }],
          checkInQuestion: {
            question: 'string',
            type: 'multipleChoice',
            options: ['A', 'B', 'C', 'D'],
            correctAnswer: 'string — must match one option exactly',
            explanation: 'string',
          },
          externalSearchSuggestions: ['youtube query 1', 'youtube query 2'],
          transitionText: 'string — bridge to next section (empty on last section)',
        },
      ],
      totalSections: 'number — must equal sections.length',
      estimatedMinutes: 'number — realistic reading time (e.g. 12-25)',
    },
  });
}

export const LEARNING_GUIDE_RETRY_SUFFIX =
  '\n\nYour previous response failed validation. Return ONLY compact valid JSON. Each section needs 280+ word explanation, exactly 1 workedExample, checkIn with 4 options, and 2 YouTube queries.';
