/** Common intended majors / fields of study for college applications */
export const COLLEGE_MAJORS = [
  'Accounting',
  'Aerospace Engineering',
  'African American Studies',
  'Agriculture',
  'American Studies',
  'Anthropology',
  'Architecture',
  'Art History',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Classics',
  'Cognitive Science',
  'Communications',
  'Computer Engineering',
  'Computer Science',
  'Creative Writing',
  'Criminal Justice',
  'Data Science',
  'Dance',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English',
  'Environmental Engineering',
  'Environmental Science',
  'Film & Media Studies',
  'Finance',
  'Fine Arts',
  'Food Science',
  'Forestry',
  'Gender Studies',
  'Geography',
  'Geology',
  'Graphic Design',
  'History',
  'Hospitality Management',
  'Human Biology',
  'Industrial Engineering',
  'Information Systems',
  'International Relations',
  'Journalism',
  'Kinesiology',
  'Linguistics',
  'Management',
  'Marketing',
  'Materials Science',
  'Mathematics',
  'Mechanical Engineering',
  'Music',
  'Neuroscience',
  'Nursing',
  'Nutrition',
  'Philosophy',
  'Physics',
  'Political Science',
  'Pre-Dentistry',
  'Pre-Law',
  'Pre-Medicine',
  'Pre-Veterinary',
  'Psychology',
  'Public Health',
  'Public Policy',
  'Religious Studies',
  'Robotics',
  'Social Work',
  'Sociology',
  'Software Engineering',
  'Sports Management',
  'Statistics',
  'Theater',
  'Urban Planning',
  'Undecided',
  'Other',
].sort((a, b) => {
  if (a === 'Undecided') return 1;
  if (b === 'Undecided') return -1;
  if (a === 'Other') return 1;
  if (b === 'Other') return -1;
  return a.localeCompare(b);
});
