import { X } from 'lucide-react';
import { usePreferences } from '@/hooks/queries/usePreferences';
import { useDismissHint } from '@/hooks/useDismissHint';
import { HINT_JOURNEY_DETAIL_GUIDE, hasHintShown } from '@/utils/preferences/hintsShown';

export default function JourneyDetailGuideBanner() {
  const { data: preferences } = usePreferences();
  const { dismiss } = useDismissHint(HINT_JOURNEY_DETAIL_GUIDE);

  if (hasHintShown(preferences, HINT_JOURNEY_DETAIL_GUIDE)) return null;

  return (
    <div className="journey-detail-guide-banner" role="region" aria-label="Getting started guide">
      <div className="journey-detail-guide-banner-copy">
        <p className="journey-detail-guide-banner-title">How this journey works</p>
        <ul className="journey-detail-guide-banner-list">
          <li>
            <strong>Modules</strong> are the individual topics or units inside your journey.
          </li>
          <li>
            <strong>Due Today</strong> reflects what spaced repetition has scheduled based on your progress.
          </li>
          <li>
            Your <strong>study plan</strong> was generated by AI and adapts as you study.
          </li>
        </ul>
      </div>
      <button
        type="button"
        className="journey-detail-guide-banner-dismiss"
        onClick={dismiss}
        aria-label="Dismiss guide"
      >
        <X size={16} />
      </button>
    </div>
  );
}
